RETRIEVE_ACTION_TYPE = "retrieve_action_type"
ADD_TASK = "add_task"
GET_TASKS = "get_tasks"
GET_TASK_FOR_DELETE = "get_task_for_delete"
GET_TASK_FOR_MODIFY = "get_task_for_modify"
GET_ALL_TASKS = "get_all_tasks"
CREATE_TASK = "create_task"
DELETE_TASK = "delete_task"
